### ISSUE TITLE
"id:" option

### ISSUE THREAD

**Issue by furio** [embulk/embulk-output-elasticsearch#22]
Maybe i don't undesrtand it well, but i don't see an example.. what i'm supposed to put there?

> id: document id column (string, default is null)

if it's a column name, it doesn't seems working, if it's type neither

```
out:
  type: elasticsearch
  index: tlddata
  index_type: data
  id: fullname
  nodes:
    - {host: 10.12.9.196}
```

Version of embulk: 0.1.8
With it I always get (without the writing it is fine):

```
org.embulk.exec.PartialExecutionException: java.lang.IllegalStateException: id is not included in column names of the Schema.
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:363)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:572)
        at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:374)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:370)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:370)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
        at RUBY.run(C:/Devstage/Embulk/embulk.bat!/embulk/runner.rb:84)
        at RUBY.run(C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_run.rb:306)
        at RUBY.<top>(C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_main.rb:2)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:939)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at C_3a_.Devstage.Embulk.embulk_dot_bat.embulk.command.embulk_bundle.<top>(file:/C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_bundle.rb:51)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:479)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:410)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:406)
                at org.embulk.spi.Exec.doWith(Exec.java:25)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:406)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:184)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:452)
                at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:313)
                at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:127)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:113)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
                at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
                at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:419)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:322)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
                at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:197)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:183)
                at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
                at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:102)
                at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:89)
                at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:32)
                at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
                at org.jruby.Ruby.runInterpreter(Ruby.java:837)
                at org.jruby.Ruby.loadFile(Ruby.java:2900)
                at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:236)
                at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:35)
                at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:896)
                at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:541)
                at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:426)
                at org.jruby.runtime.load.LoadService.require(LoadService.java:392)
                at org.jruby.RubyKernel.requireCommon(RubyKernel.java:946)
                at org.jruby.RubyKernel.require19(RubyKernel.java:939)
                at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
                at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:380)
                at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:290)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
                at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:83)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:197)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:183)
                at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at C_3a_.Devstage.Embulk.embulk_dot_bat.embulk.command.embulk_bundle.invokeOther66:require(file:/C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_bundle.rb)
                at C_3a_.Devstage.Embulk.embulk_dot_bat.embulk.command.embulk_bundle.RUBY$script(file:/C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_bundle.rb:51)
                at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
                at org.jruby.ir.Compiler$1.load(Compiler.java:111)
                at org.jruby.Ruby.runScript(Ruby.java:821)
                at org.jruby.Ruby.runScript(Ruby.java:813)
                at org.jruby.Ruby.runNormally(Ruby.java:751)
                at org.jruby.Ruby.runFromMain(Ruby.java:573)
                at org.jruby.Main.doRunFromMain(Main.java:409)
                at org.jruby.Main.internalRun(Main.java:304)
                at org.jruby.Main.run(Main.java:233)
                at org.jruby.Main.main(Main.java:200)
                at org.embulk.cli.Main.main(Main.java:23)
Caused by: java.lang.IllegalStateException: id is not included in column names of the Schema.
        at com.google.common.base.Preconditions.checkState(com/google/common/base/Preconditions.java:173)
        at org.embulk.output.elasticsearch.ElasticsearchOutputPlugin.transaction(org/embulk/output/elasticsearch/ElasticsearchOutputPlugin.java:122)
        at org.embulk.exec.BulkLoader$4$1$1.transaction(org/embulk/exec/BulkLoader.java:529)
        at org.embulk.exec.LocalExecutorPlugin.transaction(org/embulk/exec/LocalExecutorPlugin.java:54)
        at org.embulk.exec.BulkLoader$4$1.run(org/embulk/exec/BulkLoader.java:524)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:96)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at org.embulk.filter.ColumnFilterPlugin.transaction(org/embulk/filter/ColumnFilterPlugin.java:191)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at RUBY.block in transaction(C:/Devstage/Embulk/embulk.bat!/embulk/filter_plugin.rb:54)
        at RUBY.transaction(C:/Users/furio/.embulk/jruby/2.2.0/gems/embulk-filter-ruby_proc-0.1.1/lib/embulk/filter/ruby_proc.rb:23)
        at RUBY.transaction(C:/Devstage/Embulk/embulk.bat!/embulk/filter_plugin.rb:51)
        at Embulk$$FilterPlugin$$JavaAdapter_1259272679.transaction(Embulk$$FilterPlugin$$JavaAdapter_1259272679.gen:13)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at org.embulk.filter.distinct.DistinctFilterPlugin.transaction(org/embulk/filter/distinct/DistinctFilterPlugin.java:53)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at org.embulk.filter.RowFilterPlugin.transaction(org/embulk/filter/RowFilterPlugin.java:80)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at RUBY.block in transaction(C:/Devstage/Embulk/embulk.bat!/embulk/filter_plugin.rb:54)
        at RUBY.transaction(C:/Users/furio/.embulk/jruby/2.2.0/gems/embulk-filter-ruby_proc-0.1.1/lib/embulk/filter/ruby_proc.rb:23)
        at RUBY.transaction(C:/Devstage/Embulk/embulk.bat!/embulk/filter_plugin.rb:51)
        at Embulk$$FilterPlugin$$JavaAdapter_1259272679.transaction(Embulk$$FilterPlugin$$JavaAdapter_1259272679.gen:13)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at org.embulk.filter.ColumnFilterPlugin.transaction(org/embulk/filter/ColumnFilterPlugin.java:191)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters$RecursiveControl$1.run(org/embulk/spi/util/Filters.java:92)
        at org.embulk.filter.RowFilterPlugin.transaction(org/embulk/filter/RowFilterPlugin.java:80)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:87)
        at org.embulk.spi.util.Filters.transaction(org/embulk/spi/util/Filters.java:49)
        at org.embulk.exec.BulkLoader$4.run(org/embulk/exec/BulkLoader.java:518)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(org/embulk/spi/FileInputRunner.java:124)
        at org.embulk.standards.CsvParserPlugin.transaction(org/embulk/standards/CsvParserPlugin.java:225)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(org/embulk/spi/FileInputRunner.java:118)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:77)
        at org.embulk.spi.util.Decoders$RecursiveControl$1.run(org/embulk/spi/util/Decoders.java:73)
        at org.embulk.standards.GzipFileDecoderPlugin.transaction(org/embulk/standards/GzipFileDecoderPlugin.java:30)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:68)
        at org.embulk.spi.util.Decoders.transaction(org/embulk/spi/util/Decoders.java:33)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(org/embulk/spi/FileInputRunner.java:115)
        at org.embulk.standards.LocalFileInputPlugin.resume(org/embulk/standards/LocalFileInputPlugin.java:79)
        at org.embulk.standards.LocalFileInputPlugin.transaction(org/embulk/standards/LocalFileInputPlugin.java:69)
        at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:65)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:513)
        at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:374)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:370)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:370)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
        at RUBY.run(C:/Devstage/Embulk/embulk.bat!/embulk/runner.rb:84)
        at RUBY.run(C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_run.rb:306)
        at RUBY.<top>(C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_main.rb:2)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at C_3a_.Devstage.Embulk.embulk_dot_bat.embulk.command.embulk_bundle.<top>(C_3a_/Devstage/Embulk/embulk_dot_bat/embulk/command/file:/C:/Devstage/Embulk/embulk.bat!/embulk/command/embulk_bundle.rb:51)
        ... 1 more

Error: java.lang.IllegalStateException: id is not included in column names of the Schema.
`
```

**Comment by sakama** [comment]
Hi.

`id` parameter is an option to set column name in your schema that you want to set as document_id of Elasticsearch.
But this option doesn't works fine at v0.1.8 and was fixed at [v0.2.0](https://github.com/muga/embulk-output-elasticsearch/blob/master/CHANGELOG.md#020---2016-01-26) (#14).

Additionally, [replace mode](https://github.com/muga/embulk-output-elasticsearch/pull/15) is not supported at v0.1.8.

Probably, you'll be able to use `id` option at Elasticsearch 1.x when [multi version](https://github.com/muga/embulk-output-elasticsearch/pull/18) support will be implemented.
If you want to use this option immediately, the best method I think is to use Elasticsearch 2.x and embulk-output-elasticsearch v0.2.x.

**Comment by furio** [comment]
Unfortunately, I'm stuck with an older ES version (otherwise i would've used  it).
Thanks for the feedback anyway I'll manage otherwise (using an index mapping not deprecated in 1.x), when multi option will be live i'll reindex :)

**Comment by sakama** [comment]
@furio We implemented multiple Elasticsearch version support at v0.4.0.
This will allow you to use `id` option and replace mode.
I once close this issue but please feel free to re-open if you have any concerns.

Thanks.
