### ISSUE TITLE
v0.3.1 can not support es5.x

### ISSUE THREAD

**Issue by wuzimei** [embulk/embulk-output-elasticsearch#29]
I updated my es from 2.x to 5.x, but embulk failed with following message:

Caused by: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.96.29.109}{10.96.29.109:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:436)
	at org.elasticsearch.action.bulk.Retry$AbstractRetryHandler.execute(Retry.java:219)
	at org.elasticsearch.action.bulk.Retry.withAsyncBackoff(Retry.java:72)
	at org.elasticsearch.action.bulk.BulkRequestHandler$AsyncBulkRequestHandler.execute(BulkRequestHandler.java:123)
	... 13 more

Error: org.embulk.output.elasticsearch.ElasticsearchOutputPlugin$ConnectionException: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.96.29.109}{10.96.29.109:9300}]]

**Comment by sakama** [comment]
Hi.

I think it's difficult to fix this error for now.

This plugin is using Transport Client to connect to clusters and this implementation seems different between 2.x to 5.x.

* 5.x https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html
* 2.x https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.4/transport-client.html

Additionally, 5.x needs Java8.
http://www.esentri.com/blog/2016/11/19/migration-elasticsearch/

And Elastic is saying as follows.

> The client must have the same major version (e.g. 2.x, or 5.x) as the nodes in the cluster. Clients may connect to clusters which have a different minor version (e.g. 2.3.x) but it is possible that new functionality may not be supported. Ideally, the client should have the same version as the cluster.
[Client | Java API [5.1] | Elastic](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html)

It may possible to support all cluster version by using law level REST API but I'm not perfectly sure.

**Comment by kilnamkim** [comment]
@sakama 
This plugin didn't have `user`, `password` field not yet. How can i put authorization information?

**Comment by sakama** [comment]
@kilnamkim Sorry but this plugin doesn't support any auth method for now.
We're considering to support [Shield](https://www.elastic.co/guide/en/shield/current/setting-up-authentication.html) or something.

**Comment by sakama** [comment]
@wuzimei @kilnamkim Sorry to take long time.
We supports multiple Elasticsearch versions and basic authentication at v0.4.0.
https://rubygems.org/gems/embulk-output-elasticsearch/versions/0.4.0
